### ISSUE TITLE
Grant Application - (123, abc)

### ISSUE THREAD

**Issue by NerdGGuy** [NerdGGuy/zpreview#11]
### Terms and Conditions

- [X] I agree to the [Grant Agreement]() terms if funded
- [X] I agree to [Provide KYC information]() if funded above $50,000 USD
- [X] I agree to disclose conflicts of interest
- [X] I agree to adhere to the [Code of Conduct]()
- [X] I agree to post request details on the [Community Forum]()
- [X] _Link to this issue on forum (do after application has been submitted)

### Organization Name

Abc

### Application Owners (GitHub @Usernames)

@nerdgguy

### How did you learn about Zcash Community Grants

qwe

### Project Name

qwe

### Requested Grant Amount (USD)

123

### Category

Infrastructure

### Sponsorship Request

Yes

### Project Lead

Name:123
Role:123
Background:123
Responsibilities:123

### Additional Team Members

1. Name:123
   Role:123
   Background:123
   Responsibilities:
2. Name:
   Role:
   Background:
   Responsibilities:

### Project Summary

123

### Project Description

123

### Proposed Problem

123

### Proposed Solution

123

### Solution Format

123

### Dependencies

123

### Technical Approach

123

### Collaboration and Upstream Dependencies

123

### Hardware/Software Costs (USD)

123

### Hardware/Software Justification

123

### Service Costs (USD)

123

### Service Costs Justification

123

### Compensation Costs (USD)

123

### Compensation Costs Justification

123

### Total Budget (USD)

123

### Previous Funding

Yes

### Previous Funding Details

123

### Other Funding Sources

Yes

### Implementation Risks

123

### Potential Side Effects

123

### Success Metrics

123

### Timeline Overview

123

### Startup Funding (USD)

123

### Startup Funding Justification

123

### Milestone Details

1. Milestone 1
- Title:
- Amount (USD): $
- Expected Start Date: (YYYY-MM-DD)
- Expected Completion Date: (YYYY-MM-DD)
- Estimated Hours: HHHH
- Deliverables: (Provide a brief summary)
- _Status: ("", "In Progress", "Complete", "Cancelled")

2. Milestone 2
- Title:
- Amount (USD): $
- Expected Start Date: (YYYY-MM-DD)
- Expected Completion Date: (YYYY-MM-DD)
- Estimated Hours: HHHH
- Deliverables: (Provide a brief summary)
- _Status: ("", "In Progress", "Complete", "Cancelled")

### Supporting Documents

- File Name 1: Brief description of the file contents
- File Name 2: Brief description of the file contents

**Comment by NerdGGuy** [comment]
This grant looks great

**Comment by NerdGGuy** [comment]
Oh can you please explain the grant in more detail blah lbha?

**Comment by NerdGGuy** [comment]
This is fully paid out and complete
