### ISSUE TITLE
Grant Application - Danika's test application

### ISSUE THREAD

**Issue by Duhneekuh** [NerdGGuy/zpreview#18]
### Terms and Conditions

- [X] I agree to the [Grant Agreement]() terms if funded
- [X] I agree to [Provide KYC information]() if funded above $50,000 USD
- [X] I agree to disclose conflicts of interest
- [X] I agree to adhere to the [Code of Conduct]()
- [X] I agree to post request details on the [Community Forum]()
- [X] _Link to this issue on forum (do after application has been submitted)

### Organization Name

org name test

### Application Owners (GitHub @Usernames)

@Duhneekuh

### How did you learn about Zcash Community Grants

ZF

### Project Name

Test project name

### Requested Grant Amount (USD)

$10,000

### Category

Research & Development

### Sponsorship Request

No

### Project Lead

Name: Danika
Role: Operations Director
Background: Operations Director at ZF
Responsibilities: testing this application, yadda yadda yadda

### Additional Team Members

1. Name: Alex Bornstein
   Role: ZF COO
   Background: ZF COO
   Responsibilities: testing this application, yadda yadda yadda
2. Name:
   Role:
   Background:
   Responsibilities:

### Project Summary

project summary test

### Project Description

project description test

### Proposed Problem

proposed problem test

### Proposed Solution

proposed solution test

### Solution Format

solution format test

### Dependencies

dependencies test

### Technical Approach

technical approach test

### Collaboration and Upstream Dependencies

collaboration test

### Hardware/Software Costs (USD)

0

### Hardware/Software Justification

yadda yadda yadda

### Service Costs (USD)

0

### Service Costs Justification

yadda yadda yadda

### Compensation Costs (USD)

10000

### Compensation Costs Justification

yadda yadda yadda

### Total Budget (USD)

10000

### Previous Funding

Yes

### Previous Funding Details

yadda yadda yadda

### Other Funding Sources

Yes

### Implementation Risks

yadda yadda yadda

### Potential Side Effects

yadda yadda yadda

### Success Metrics

yadda yadda yadda

### Timeline Overview

yadda yadda yadda

### Startup Funding (USD)

10000

### Startup Funding Justification

yadda yadda yadda

### Milestone Details

NA

### Supporting Documents

NA
